//! Butterworth IIR sections (biquad cascade) — the `scipy.signal.butter` +
//! `sosfilt` replacement for the Rust port.
//!
//! Designed by bilinear transform with frequency pre-warping, matching the
//! standard analog Butterworth pole layout. A cascade of `order / 2` biquads
//! gives an even-order response; the bandpass is a highpass ∘ lowpass cascade
//! rather than scipy's true bandpass pole mapping. That is a deliberate
//! simplification: callers here shape noise fixtures and hunt birdies, where the
//! passband edges matter and the exact transition-band ripple does not. It does
//! mean coefficients are *not* bit-identical to scipy's — fixtures generated by
//! this module are self-consistent and deterministic, but a hash computed under
//! the Python original will not match.

use crate::dsp::DspError;

/// One second-order section in direct-form II transposed.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Biquad {
    b0: f64,
    b1: f64,
    b2: f64,
    a1: f64,
    a2: f64,
}

impl Biquad {
    /// Build from unnormalized coefficients, dividing through by `a0`.
    fn from_raw(b0: f64, b1: f64, b2: f64, a0: f64, a1: f64, a2: f64) -> Self {
        Self {
            b0: b0 / a0,
            b1: b1 / a0,
            b2: b2 / a0,
            a1: a1 / a0,
            a2: a2 / a0,
        }
    }

    /// Filter `x` in place through this section, starting from zero state.
    fn process(&self, x: &mut [f64]) {
        let (mut s1, mut s2) = (0.0f64, 0.0f64);
        for v in x.iter_mut() {
            let input = *v;
            let out = self.b0 * input + s1;
            s1 = self.b1 * input - self.a1 * out + s2;
            s2 = self.b2 * input - self.a2 * out;
            *v = out;
        }
    }
}

/// A cascade of biquads applied in series.
#[derive(Debug, Clone, PartialEq)]
pub struct Sos(Vec<Biquad>);

impl Sos {
    /// Filter `x` in place (single pass, zero initial state — not zero-phase).
    pub fn filter(&self, x: &mut [f64]) {
        for section in &self.0 {
            section.process(x);
        }
    }

    /// Number of second-order sections.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

/// Validate a cutoff and return the pre-warped analog frequency `tan(pi * fc / fs)`.
fn prewarp(cutoff_hz: f64, sr: u32, what: &str) -> Result<f64, DspError> {
    if sr == 0 {
        return Err(DspError::new("sr must be positive"));
    }
    let nyquist = sr as f64 / 2.0;
    if !(cutoff_hz > 0.0 && cutoff_hz < nyquist) {
        return Err(DspError::new(format!(
            "{what} cutoff {cutoff_hz} Hz must be in (0, {nyquist}) for sr {sr}"
        )));
    }
    Ok((std::f64::consts::PI * cutoff_hz / sr as f64).tan())
}

/// Butterworth pole damping for section `k` of an `order`-pole cascade.
///
/// The analog Butterworth poles sit evenly on the unit semicircle; each conjugate
/// pair contributes `2*cos(theta)` to the denominator's `s` term.
fn butter_damping(order: usize, k: usize) -> f64 {
    let theta = std::f64::consts::PI * (2.0 * k as f64 + 1.0) / (2.0 * order as f64);
    2.0 * theta.sin()
}

/// Even-order Butterworth lowpass.
///
/// `order` must be even and non-zero; `cutoff_hz` strictly inside `(0, sr/2)`.
pub fn butter_lowpass(order: usize, cutoff_hz: f64, sr: u32) -> Result<Sos, DspError> {
    if order == 0 || order % 2 != 0 {
        return Err(DspError::new(format!("order {order} must be even and > 0")));
    }
    let w = prewarp(cutoff_hz, sr, "lowpass")?;
    let (w2, sections) = (w * w, order / 2);
    let mut out = Vec::with_capacity(sections);
    for k in 0..sections {
        // H(s) = w^2 / (s^2 + d*w*s + w^2), bilinear-transformed with s -> (1-z^-1)/(1+z^-1).
        let d = butter_damping(order, k);
        let a0 = 1.0 + d * w + w2;
        out.push(Biquad::from_raw(
            w2,
            2.0 * w2,
            w2,
            a0,
            2.0 * (w2 - 1.0),
            1.0 - d * w + w2,
        ));
    }
    Ok(Sos(out))
}

/// Even-order Butterworth highpass.
pub fn butter_highpass(order: usize, cutoff_hz: f64, sr: u32) -> Result<Sos, DspError> {
    if order == 0 || order % 2 != 0 {
        return Err(DspError::new(format!("order {order} must be even and > 0")));
    }
    let w = prewarp(cutoff_hz, sr, "highpass")?;
    let (w2, sections) = (w * w, order / 2);
    let mut out = Vec::with_capacity(sections);
    for k in 0..sections {
        // Same poles as the lowpass; the numerator becomes s^2 -> (1 - z^-1)^2.
        let d = butter_damping(order, k);
        let a0 = 1.0 + d * w + w2;
        out.push(Biquad::from_raw(
            1.0,
            -2.0,
            1.0,
            a0,
            2.0 * (w2 - 1.0),
            1.0 - d * w + w2,
        ));
    }
    Ok(Sos(out))
}

/// Bandpass as a highpass ∘ lowpass cascade (see the module note on scipy parity).
///
/// `order` is the order of *each* leg, so the skirts fall at `order` poles per side.
pub fn butter_bandpass(order: usize, low_hz: f64, high_hz: f64, sr: u32) -> Result<Sos, DspError> {
    if low_hz >= high_hz {
        return Err(DspError::new(format!(
            "bandpass low {low_hz} Hz must be below high {high_hz} Hz"
        )));
    }
    let mut sections = butter_highpass(order, low_hz, sr)?;
    sections.0.extend(butter_lowpass(order, high_hz, sr)?.0);
    Ok(sections)
}
